2025-06-16 23:29:38,106 INFO    MainThread:69550 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-06-16 23:29:38,106 INFO    MainThread:69550 [wandb_setup.py:_flush():81] Configure stats pid to 69550
2025-06-16 23:29:38,106 INFO    MainThread:69550 [wandb_setup.py:_flush():81] Loading settings from /Users/jdieguez/.config/wandb/settings
2025-06-16 23:29:38,106 INFO    MainThread:69550 [wandb_setup.py:_flush():81] Loading settings from /Users/jdieguez/Documents/master/TFM/code/TFM-SemFew/Model/wandb/settings
2025-06-16 23:29:38,106 INFO    MainThread:69550 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-16 23:29:38,106 INFO    MainThread:69550 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /Users/jdieguez/Documents/master/TFM/code/TFM-SemFew/Model/wandb/run-20250616_232938-6l9klnid/logs/debug.log
2025-06-16 23:29:38,106 INFO    MainThread:69550 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /Users/jdieguez/Documents/master/TFM/code/TFM-SemFew/Model/wandb/run-20250616_232938-6l9klnid/logs/debug-internal.log
2025-06-16 23:29:38,106 INFO    MainThread:69550 [wandb_init.py:monkeypatch_ipython():622] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x194b6cb20>
2025-06-16 23:29:38,107 INFO    MainThread:69550 [wandb_init.py:init():831] calling init triggers
2025-06-16 23:29:38,107 INFO    MainThread:69550 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'dataset': 'MiniImageNet', 'backbone': 'resnet', 'center': 'mean', 'gpu': 0, 'project': 'SemFew_recreate', 'run_name': 'FC100_default', 'path_to_checkpoints': '/Users/jdieguez/Documents/master/TFM/code/checkpoints', 'path_to_cifarfs': '/Users/jdieguez/Documents/master/TFM/code/cifar-fs/', 'path_to_fc100': '/Users/jdieguez/Documents/master/TFM/code/FC100/', 'path_to_miniimagenet': '/Users/jdieguez/Documents/master/TFM/code/miniimagenet', 'path_to_tieredimagenet': '/path/to/your/tiredimagenet', 'llm': 'default', 'semantics_from': 'default', 'file': 'None', 'key': 'None', 'images_per_class': 5, 'verbose': False, 'max_epoch': 1, 'test_batch': 600, 'shot': 1, 'query': 15, 'test_way': 5, 'feat_size': 640, 'semantic_size': 512, 'batch_size': 128, 'num_workers': 8, 'drop': 0.0, 'lr': 0.0001, 'step_size': 30, 'mode': 'clip', 'text_type': 'gpt', 'test-batch': 600, 'seed': 13, 'model_path': '/Users/jdieguez/Documents/master/TFM/code/checkpoints/ResNet-MiniImageNet.pth', '_wandb': {}}
2025-06-16 23:29:38,107 INFO    MainThread:69550 [wandb_init.py:init():872] starting backend
2025-06-16 23:29:38,340 INFO    MainThread:69550 [wandb_init.py:init():875] sending inform_init request
2025-06-16 23:29:38,365 INFO    MainThread:69550 [wandb_init.py:init():883] backend started and connected
2025-06-16 23:29:38,375 INFO    MainThread:69550 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2025-06-16 23:29:38,375 INFO    MainThread:69550 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-06-16 23:29:38,375 INFO    MainThread:69550 [wandb_init.py:init():956] updated telemetry
2025-06-16 23:29:38,413 INFO    MainThread:69550 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-06-16 23:29:38,931 INFO    MainThread:69550 [wandb_init.py:init():1032] starting run threads in backend
2025-06-16 23:29:39,081 INFO    MainThread:69550 [wandb_run.py:_console_start():2453] atexit reg
2025-06-16 23:29:39,081 INFO    MainThread:69550 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-06-16 23:29:39,082 INFO    MainThread:69550 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-06-16 23:29:39,082 INFO    MainThread:69550 [wandb_run.py:_redirect():2393] Redirects installed.
2025-06-16 23:29:39,086 INFO    MainThread:69550 [wandb_init.py:init():1078] run started, returning control to user process
2025-06-16 23:29:40,359 INFO    MainThread:69550 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-16 23:30:33,115 INFO    MsgRouterThr:69550 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-06-16 23:30:33,841 ERROR   Thread-2  :69550 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2374, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/jdieguez/anaconda3/envs/tfm2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
